<a href="https://colab.research.google.com/github/BrendenLatham/Data_Viz/blob/main/ExamReview.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Processing and Visualization Exam Review

In [3]:
from google.colab import auth
auth.authenticate_user()
print('authenticated')

authenticated

## 1

### a

In [5]:
%%bigquery --project data-viz-338801

SELECT *
FROM bigquery-public-data.london_fire_brigade.fire_brigade_service_calls
limit 5

   incident_number  ... num_pumps_attending
0  000320-01012017  ...                   2
1  003727-09012017  ...                   2
2  003762-09012017  ...                   2
3  006403-16012017  ...                   2
4  010947-26012017  ...                   1

[5 rows x 32 columns]

In [8]:
%%bigquery --project data-viz-338801

SELECT count(*) as Entries
FROM bigquery-public-data.london_fire_brigade.fire_brigade_service_calls

   Entries
0    32247

### b

In [25]:
%%bigquery --project data-viz-338801
with w as (
  with q as (
    with t as (
      SELECT incident_group as Incident, hour_of_call as Hour
      FROM bigquery-public-data.london_fire_brigade.fire_brigade_service_calls
    )
    SELECT Incident, Hour
    FROM t
    GROUP BY Hour, Incident
    HAVING Hour BETWEEN 10 and 12 or Hour BETWEEN 1 and 4
  )
  SELECT *
  FROM q
  GROUP BY HOUR, Incident
  HAVING Incident = "False Alarm"
)
SELECT count(*) as FalseAlarmsFrom10to5
FROM w

   FalseAlarmsFrom10to5
0                     7