<a href="https://colab.research.google.com/github/BrendenLatham/Data_Viz/blob/main/Assignment17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 17

Once again I will first import my packages and dataset

In [ ]:
import pandas as pd
import statistics as stat
df = pd.read_csv('https://raw.githubusercontent.com/nurfnick/Data_Viz/main/iris.csv')

In [ ]:
df.head()

   SepalLength  SepalWidth  PedalLength  PedalWidth        Class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

I am going to be examining types. I will start with how the mean is effected when going from float to int

In [ ]:
print("as float: ",stat.mean(df.SepalLength))
print("as int: ", stat.mean(df.SepalLength.astype('int')))

as float:  5.843333333333334
as int:  5.386666666666667

It looks like it did change it by roughly .46

I want to see if the same happens when I group by Class

In [ ]:
df.groupby('Class').SepalLength.agg(['mean'])

                  mean
Class
Iris-setosa      5.006
Iris-versicolor  5.936
Iris-virginica   6.588

In [ ]:
df2 = df
df2.SepalLength = df2.SepalLength.astype('int')
df2.groupby('Class').SepalLength.agg(['mean'])

                 mean
Class
Iris-setosa      4.60
Iris-versicolor  5.48
Iris-virginica   6.08

It looks like the shift was in the same direction

Now I will gather the mean, median, count, and standard deviation of all columns when grouped by class

In [ ]:
df.groupby('Class').agg(['mean','median','count','std'])

                SepalLength               ... PedalWidth
                       mean median count  ...     median count       std
Class                                     ...
Iris-setosa            4.60    5.0    50  ...        0.2    50  0.107210
Iris-versicolor        5.48    5.0    50  ...        1.3    50  0.197753
Iris-virginica         6.08    6.0    50  ...        2.0    50  0.274650

[3 rows x 16 columns]

That was a nice and short lesson. I would have liked to play around with the code more but unfortunately I have other classes that are screaming for my attention.